name: CI

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.14.0
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - run: pnpm install --frozen-lockfile
      - run: pnpm quality.check
      - run: pnpm -r test
